
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author intel
 */
public class Home extends javax.swing.JFrame {

    String str1,str2;
        int s,t,a,z,tab=500000;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ss = new javax.swing.JLabel();
        tarik = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        ceksal = new javax.swing.JButton();
        setor = new javax.swing.JButton();
        bantu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        transf.setBackground(new java.awt.Color(0, 204, 255));
        transf.setText("<");
        transf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfActionPerformed(evt);
            }
        });
        getContentPane().add(transf);
        transf.setBounds(380, 170, 50, 30);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel1.setText("TRANSAKSI");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 160, 50);

        jLabel2.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jLabel2.setText("Transfer");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 170, 120, 30);

        jl.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jl.setText("Penarikan");
        getContentPane().add(jl);
        jl.setBounds(280, 230, 120, 40);

        jLabel4.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jLabel4.setText("Cek Saldo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 100, 80, 30);

        jLabel.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jLabel.setText("Bantuan");
        getContentPane().add(jLabel);
        jLabel.setBounds(70, 170, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jLabel6.setText("Exit");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 230, 120, 40);

        ss.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        ss.setText("Penyetoran");
        getContentPane().add(ss);
        ss.setBounds(70, 100, 110, 30);

        tarik.setBackground(new java.awt.Color(0, 204, 255));
        tarik.setText("<");
        tarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarikActionPerformed(evt);
            }
        });
        getContentPane().add(tarik);
        tarik.setBounds(380, 230, 50, 30);

        exit.setBackground(new java.awt.Color(0, 204, 255));
        exit.setText(">");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(0, 240, 50, 30);

        ceksal.setBackground(new java.awt.Color(0, 204, 255));
        ceksal.setText("<");
        ceksal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceksalActionPerformed(evt);
            }
        });
        getContentPane().add(ceksal);
        ceksal.setBounds(380, 100, 50, 30);

        setor.setBackground(new java.awt.Color(0, 204, 255));
        setor.setText(">");
        setor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setorActionPerformed(evt);
            }
        });
        getContentPane().add(setor);
        setor.setBounds(0, 100, 50, 30);

        bantu.setBackground(new java.awt.Color(0, 204, 255));
        bantu.setText(">");
        bantu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bantuActionPerformed(evt);
            }
        });
        getContentPane().add(bantu);
        bantu.setBounds(0, 170, 50, 30);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 0, 310, 360);

        setBounds(0, 0, 446, 386);
    }// </editor-fold>//GEN-END:initComponents

    private void ceksalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceksalActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : " + tab); //informasi saldo
z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BRI - Malang", JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
if (z==0)
{
      new Home().show();
      this.dispose();
}
else{
JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BRI - Malang, ambil kartu ATM Anda.");
System.exit(0);
}
    }//GEN-LAST:event_ceksalActionPerformed

    private void tarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarikActionPerformed
        // TODO add your handling code here:
        
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan : " ); //pengambilan
        t = Integer.parseInt(str1);
        tarik mengambil = new tarik();
        mengambil.ambil(tab,t);
        tab =mengambil.getsaldo();
        z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BRI - Malang", JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
        if (z==0)
        {
            new Home().show();
            this.dispose();
        }
        else{
        JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BRI - Malang, ambil kartu ATM Anda");
        System.exit(0);
        }
    }//GEN-LAST:event_tarikActionPerformed

    private void setorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setorActionPerformed
        // TODO add your handling code here:
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran: " ); //menabung
        s = Integer.parseInt(str1);
        setor hasil = new setor();
        hasil.menabung(tab, s);
        tab =hasil.getsaldo();
        z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BRI - Malang", JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
        if (z==0)
        {
            new Home().show();
            this.dispose();
        }
        else{
        JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BRI - Malang, ambil kartu ATM Anda");
        System.exit(0);
                }
    }//GEN-LAST:event_setorActionPerformed

    private void bantuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bantuActionPerformed
        // TODO add your handling code here:
        new bantuan().show();
        this.dispose();
    }//GEN-LAST:event_bantuActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BRI - Malang, ambil kartu ATM Anda");
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void transfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfActionPerformed
        // TODO add your handling code here:
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah transfer : ");
        str2 = JOptionPane.showInputDialog(null,"Masukkan rekening tujuan : ");//pengambilan
        a = JOptionPane.showConfirmDialog(null,"Transfer anda berhasilpada rekening : "+str2+" sebesar "+str1);
        t = Integer.parseInt(str1);
        transfer mengambil = new transfer();
        mengambil.transfer(tab,t);
        tab =mengambil.getsaldo();
        
        z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BRI - Malang", 
                JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
        if (z==0)
        {
            new Home().show();
            this.dispose();
        }
        else{
        JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BRI - Malang, ambil kartu ATM Anda");
        System.exit(0);
        }
    }//GEN-LAST:event_transfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bantu;
    private javax.swing.JButton ceksal;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jl;
    private javax.swing.JButton setor;
    private javax.swing.JLabel ss;
    private javax.swing.JButton tarik;
    private javax.swing.JButton transf;
    // End of variables declaration//GEN-END:variables
}
